variable "ebs_volume_name" { }
variable "volume_size" { }
variable "volume_type" { }
variable "volume_iops" { }
variable "volume_throughput" { }
variable "device_name" { }
variable "Environment" { }
variable "Account" { }
variable "ManagedBy" { }
variable "ec2_instance_id" { }
variable "ebs_volume_kms_name" { }
variable "network_interface_1_subnet_name" { }
variable "volume_encrypted" { }