variable "role_name" { }
variable "network_interface_name" { }
variable "ec2_instance_name" { }
variable "ebs_volume_kms_name" { }
variable "Environment" { }
variable "Account" { }
variable "ManagedBy" { }
variable "network_interface_1_private_ips" { }
variable "network_interface_1_subnet_name" { }
variable "ec2_instance_disable_api_termination" { }
variable "ec2_instance_ebs_optimized" { }
variable "ec2_instance_monitoring" { }
variable "ec2_instance_user_data" { }
variable "ec2_instance_http_tokens" { }
variable "ec2_instance_http_put_response_hop_limit" { }
variable "security_groups_names" { }
variable "ami_name" { }
variable "instance_type" { }
variable "root_volume_name" { }
variable "root_volume_delete_on_termination" { }
variable "root_volume_encrypted" { }
variable "root_volume_size" { }
variable "root_volume_type" { }
variable "root_volume_iops" { }
variable "root_volume_throughput" { }