variable "network_interface_name" { }
variable "Environment" { }
variable "Account" { }
variable "ManagedBy" { }
variable "network_interface_subnet_name" { }
variable "eni_private_ips" { }
variable "security_groups_names" { }
variable "eni_device_index" { }
variable "ec2_instance_id" { }